Repository sekwah41/Advanced-Portals, pull requests merged in 2024-07, with the labels that each got.

#432 feat: add link to re-code progress
  .github/workflows/gradle.yml
  .gitignore
  .yarn/install-state.gz
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
  README.md
  package.json
Labels: patch

#433 chore: force changes
  README.md
Labels: patch, release

#388 feat: add custom messages to plugin
  src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
  src/main/java/com/sekwah/advancedportals/bukkit/PluginMessages.java
  src/main/java/com/sekwah/advancedportals/bukkit/destinations/Destination.java
  src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java
  src/main/java/com/sekwah/advancedportals/bukkit/listeners/PortalProtect.java
  src/main/java/com/sekwah/advancedportals/bukkit/portals/Portal.java
  src/main/resources/config.yml
  src/main/resources/messages.yml
Labels: release

#397 FIX: Remove HAS_WARPED Metadata when logging into a new server
  src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java
Labels: minor, release
